// FOR REACT-REDUX

export const ADD_SYLLABLE = 'ADD_SYMBOL'
export const SET_SYLLABLES = 'SET_SYLLABLES'
export const TEST_MSG = 'TEST_MSG'
export const GET_SYMBOLS = 'GET_SYMBOLS'
export const FILTER_SYMBOLS_BY_NAME = 'FILTER_SYMBOLS_BY_NAME'
export const FILTER_SYMBOLS_BY_OPTIONS = 'FILTER_SYMBOLS_BY_OPTIONS'
export const FILTER_SYMBOLS_BY_PITCH = 'FILTER_SYMBOLS_BY_PITCH'
export const ADD_TEXT_TO_SYLLABLE = 'ADD_TEXT_TO_SYLLABLE'

// NAMES OF SYMBOLS

export const NAMES_OF_SYMBOLS = [
  { id: 1, name: 'Параклит' },
  { id: 2, name: 'Крюк' },
  { id: 3, name: 'Запятая' },
  { id: 4, name: 'Стопица' },
  { id: 5, name: 'Челюстка' },
  { id: 6, name: 'Ключ' },
  { id: 7, name: 'Подчашие' },
  { id: 8, name: 'Палка' },
  { id: 9, name: 'Скамейца' },
  { id: 10, name: 'Дербица' },
  { id: 11, name: 'Переводка' },
  { id: 12, name: 'Голубчик борзый' },
  { id: 13, name: 'Голубчик тихий' },
  { id: 14, name: 'Чашка' },
  { id: 15, name: 'Статья' },
  { id: 16, name: 'Статья светлая' },
  { id: 17, name: 'Статья с запятой' },
  { id: 18, name: 'Статья мрачная' },
  { id: 19, name: 'Малая закрытая' },
  { id: 20, name: 'Средняя закрытая' },
  { id: 21, name: 'Крыж' },
  { id: 22, name: 'Рог' },
  { id: 23, name: 'Сложитие' },
  { id: 24, name: 'Сложитие с купной' },
  { id: 25, name: 'Сложитие с запятой' },
  { id: 26, name: 'Полукулизма' },
  { id: 27, name: 'Два в челну' },
  { id: 28, name: 'Труба' },
  { id: 29, name: 'Дуда' },
  { id: 30, name: 'Мечник' },
  { id: 31, name: 'Стрела мрачная' },
  { id: 32, name: 'Стрела крыжевая' },
  { id: 33, name: 'Стрела поводная' },
  { id: 34, name: 'Стрела светлая' },
  { id: 35, name: 'Статья тресветлая' },
  { id: 36, name: 'Стрела светлотихая' },
  { id: 37, name: 'Стрела поездная' },
  { id: 38, name: 'Стрела громная' },
  { id: 39, name: 'Стрела громосветлая' },
  { id: 40, name: 'Стрела громотресветлая' },
  { id: 41, name: 'Стрела возводная' },
  { id: 42, name: 'Стрела громокрыжная' },
  { id: 43, name: 'Стрела трясосветлая' },
  { id: 44, name: 'Хамило' },
  { id: 45, name: 'Паук малый' },
  { id: 46, name: 'Паук большой' },
  { id: 47, name: 'Фита' },
  { id: 48, name: 'Полукулизма малая' },
  { id: 49, name: 'Фотиза' },
  { id: 50, name: 'Змийца' },
]


export const SYMBOLS = [
  { value: 1, label: 'Параклит' },
  { value: 2, label: 'Крюк' },
  { value: 3, label: 'Запятая' },
  { value: 4, label: 'Стопица' },
  { value: 5, label: 'Челюстка' },
  { value: 6, label: 'Ключ' },
  { value: 7, label: 'Подчашие' },
  { value: 8, label: 'Палка' },
  { value: 9, label: 'Скамейца' },
  { value: 10, label: 'Дербица' },
  { value: 11, label: 'Переводка' },
  { value: 12, label: 'Голубчик борзый' },
  { value: 13, label: 'Голубчик тихий' },
  { value: 14, label: 'Чашка' },
  { value: 15, label: 'Статья' },
  { value: 16, label: 'Статья светлая' },
  { value: 17, label: 'Статья с запятой' },
  { value: 18, label: 'Статья мрачная' },
  { value: 19, label: 'Малая закрытая' },
  { value: 20, label: 'Средняя закрытая' },
  { value: 21, label: 'Крыж' },
  { value: 22, label: 'Рог' },
  { value: 23, label: 'Сложитие' },
  { value: 24, label: 'Сложитие с купной' },
  { value: 25, label: 'Сложитие с запятой' },
  { value: 26, label: 'Полукулизма' },
  { value: 27, label: 'Два в челну' },
  { value: 28, label: 'Труба' },
  { value: 29, label: 'Дуда' },
  { value: 30, label: 'Мечник' },
  { value: 31, label: 'Стрела мрачная' },
  { value: 32, label: 'Стрела крыжевая' },
  { value: 33, label: 'Стрела поводная' },
  { value: 34, label: 'Стрела светлая' },
  { value: 35, label: 'Статья тресветлая' },
  { value: 36, label: 'Стрела светлотихая' },
  { value: 37, label: 'Стрела поездная' },
  { value: 38, label: 'Стрела громная' },
  { value: 39, label: 'Стрела громосветлая' },
  { value: 40, label: 'Стрела громотресветлая' },
  { value: 41, label: 'Стрела возводная' },
  { value: 42, label: 'Стрела громокрыжная' },
  { value: 43, label: 'Стрела трясосветлая' },
  { value: 44, label: 'Хамило' },
  { value: 45, label: 'Паук малый' },
  { value: 46, label: 'Паук большой' },
  { value: 47, label: 'Фита' },
  { value: 48, label: 'Полукулизма малая' },
  { value: 49, label: 'Фотиза' },
  { value: 50, label: 'Змийца' },
]

export const OPTIONS = [
  { value: 1, label: 'Борзая' },
  { value: 2, label: 'Тихая' },
  { value: 3, label: 'Качка' },
  { value: 4, label: 'Ударка' },
  { value: 5, label: 'Закидка' },
  { value: 6, label: 'Равенство' },
  { value: 7, label: 'Ломка' },
  { value: 8, label: 'Подвертка' },
  { value: 9, label: 'Отсечка' },
  { value: 10, label: 'Задержка' },
  { value: 11, label: 'Подчашие' },
  { value: 12, label: 'Облачко' },
  { value: 13, label: 'Сорочья ножка' },
]

export const PITCH = [
  { value: 1, label: 'Ут низкое' },
  { value: 2, label: 'Ре низкое' },
  { value: 3, label: 'Ми низкое' },
  { value: 4, label: 'Ут' },
  { value: 5, label: 'Ре' },
  { value: 6, label: 'Ми' },
  { value: 7, label: 'Фа' },
  { value: 8, label: 'Соль' },
  { value: 9, label: 'Ля' },
  { value: 10, label: 'Фа высокое' },
  { value: 11, label: 'Соль высокое' },
  { value: 12, label: 'Ля высокое' },
]
